### ISSUE TITLE
array of keys empty after calling createKey

### ISSUE THREAD

**Issue by fithwith** [ironSource/node-regedit#10]
after calling 
var keys=[....];
regedit.createKey(keys, function(err) {...});

the array keys is empty, why did the createKey function empty the array?

**Comment by kessler** [comment]
At some point the code empties the array when its being fed it to the stream. While its against normal best practices (such as defensive programming and such) I opted not to copy the array immediately since at times we are talking about very long arrays.

In this particular we rely on the client (i.e you) to use defensive programming.

Will update the documentation about this.

**Comment by fithwith** [comment]
ok, for my case I want to keep the keys after the creation so I cloned the array before.

Thank you for your explanation.
